=== pablo603/Xml-REPO/XML repo/Concesionario/esquema-concesionario.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--DefiniciÃ³n del documento XML-->
<g1:schema xmlns:g1="https://www.renault.es/" version="1.0"> 
    <g1:element name="concesionario">
        <g1:complexType>
            <g1:sequence>
                <g1:element name="coche" maxOccurs="unbounded">
                    <g1:complexType>
                        <g1:sequence>
                            <g1:element name ="codigo" maxOccurs="unbounded"/>
                            <g1:element name ="matricula" maxOccurs="unbounded"/>
                            <g1:element name ="marca" maxOccurs="unbounded"/>
                            <g1:element name ="modelo" maxOccurs="unbounded">
                                <g1:complexType>
                                    <g1:sequence>
                                        <g1:element name ="potencia" maxOccurs="unbounded"/>
                                        <g1:element name ="plazas" maxOccurs="unbounded"/>
                                        <g1:element name ="numpuertas" maxOccurs="unbounded"/>
                                    </g1:sequence>
                                </g1:complexType>
                            </g1:element>
                        </g1:sequence>
                    </g1:complexType>
                </g1:element>
            </g1:sequence>
        </g1:complexType>
    </g1:element>
</schema>

=== pablo603/Xml-REPO/XML repo/Concesionario/Actividad_2_tema4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--DefiniciÃ³n del documento XML-->
<concesionario xmlns:g1="https://www.renault.es/" g1:noNamespaceSchemaLocation="esquema-concesionario.xsd">
    <coche> 
        <codigo>64888974569b</codigo>
        <matricula>111bck</matricula>
        <marca>Renault</marca>
        <modelo>
            <potencia>400</potencia>
            <plazas>4</plazas>
            <numPuertas>3</numPuertas>
        </modelo>

    </coche>
    <coche> 
        <codigo>2584726842n</codigo>
        <matricula>6665bck</matricula>
        <marca>Renault</marca>
        <modelo>
            <potencia>425</potencia>
            <plazas>5</plazas>
            <numPuertas>4</numPuertas>
        </modelo>
        
    </coche> 
    <coche> 
        <codigo>333842652471x</codigo>
        <matricula>987FGH</matricula>
        <marca>Renault</marca>
        <modelo>
            <potencia>350</potencia>
            <plazas>4</plazas>
            <numPuertas>3</numPuertas>
        </modelo>       
    </coche>
</concesionario>
